### ISSUE TITLE
python manage.py makemigrations  error

### ISSUE THREAD

**Issue by phanthuthao** [signorrayan/RedTeam_toolkit#23]
python manage.py makemigrations                                                                                                                                 1 ⨯
Traceback (most recent call last):
  File "/home/monkey/RedTeam_toolkit/manage.py", line 22, in <module>
    main()
  File "/home/monkey/RedTeam_toolkit/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/monkey/RedTeam_toolkit/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/home/monkey/RedTeam_toolkit/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 369, in execute
    settings.INSTALLED_APPS
  File "/home/monkey/RedTeam_toolkit/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 84, in __getattr__
    self._setup(name)
  File "/home/monkey/RedTeam_toolkit/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 71, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/monkey/RedTeam_toolkit/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 179, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/monkey/RedTeam_toolkit/RedTeam_toolkit/settings.py", line 27, in <module>
    SECRET_KEY = config("l=s6j#f6(0*%r956dx%7fx(9@7$m_(%+kb7)ng=^4li6fhs2yt")
  File "/home/monkey/RedTeam_toolkit/venv/lib/python3.9/site-packages/decouple.py", line 206, in __call__
    return self.config(*args, **kwargs)
  File "/home/monkey/RedTeam_toolkit/venv/lib/python3.9/site-packages/decouple.py", line 90, in __call__
    return self.get(*args, **kwargs)
  File "/home/monkey/RedTeam_toolkit/venv/lib/python3.9/site-packages/decouple.py", line 75, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: l=s6j#f6(0*%r956dx%7fx(9@7$m_(%+kb7)ng=^4li6fhs2yt not found. Declare it as envvar or define a default value.

**Comment by signorrayan** [comment]
Hello.
As I see in this lines:
```
File "/home/monkey/RedTeam_toolkit/RedTeam_toolkit/settings.py", line 27, in
SECRET_KEY = config("l=s6j#f6(0*%r956dx%7fx(9@7$m(%+kb7)ng=^4li6fhs2yt")
```
you should not change `SECRET_KEY = config("SECRET_KEY")` default value. Instead of that, you should create a file `.env` in this path: `/home/monkey/RedTeam_toolkit/.env`.
inside this file, put your secret key: 
`SECRET_KEY = 'Your Secret Key'`
