### ISSUE TITLE
python manage.py makemigrations (decouple.UndefinedValueError)

### ISSUE THREAD

**Issue by Abd659** [signorrayan/RedTeam_toolkit#27]
Hi
When trying to execute this command, the following error raises:

> Traceback (most recent call last):
  File "/home/hack/RedTeam_toolkit/manage.py", line 22, in <module>
    main()
  File "/home/hack/RedTeam_toolkit/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/hack/RedTeam_toolkit/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/home/hack/RedTeam_toolkit/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 369, in execute
    settings.INSTALLED_APPS
  File "/home/hack/RedTeam_toolkit/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 84, in __getattr__
    self._setup(name)
  File "/home/hack/RedTeam_toolkit/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 71, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/hack/RedTeam_toolkit/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 179, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/hack/RedTeam_toolkit/RedTeam_toolkit/settings.py", line 27, in <module>
    SECRET_KEY = config("SECRET_KEY")
  File "/home/hack/RedTeam_toolkit/venv/lib/python3.9/site-packages/decouple.py", line 243, in __call__
    return self.config(*args, **kwargs)
  File "/home/hack/RedTeam_toolkit/venv/lib/python3.9/site-packages/decouple.py", line 105, in __call__
    return self.get(*args, **kwargs)
  File "/home/hack/RedTeam_toolkit/venv/lib/python3.9/site-packages/decouple.py", line 90, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.

And here are the files in the folder:

> Demo  LICENSE.md  manage.py  README.md  RedTeam_toolkit  requirements.txt  SECRET_KEY.env  toolkit  venv

**Comment by signorrayan** [comment]
Hi.

Change the file name `SECRET_KEY.env` to `.env`
This file should contains 1 line in the following format:

`SECRET_KEY = 'paste_your_secret_key_here'`
